In [1]:
import cobra
import pickle as pkl

In [11]:
from gem_utilities.media import clean_media

In [2]:
model = cobra.io.read_sbml_model('model.xml')

In [3]:
# Load the media definitions
with open("test/test_files/media/media_definitions.pkl", "rb") as f:
    media_definitions = pkl.load(f)

In [9]:
mbm_glucose = media_definitions['mbm'].copy()
mbm_glucose['EX_cpd00027_e0'] = 10

In [12]:
model.medium = clean_media(model, mbm_glucose)
sol_mbm_glucose = model.optimize()
sol_mbm_glucose

/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00966_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd09225_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00552_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00242_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd09695_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00240_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd28238_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00104_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00393_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00263_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00220_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00133_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00644_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd01826_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00443_e0, so it was not set in the media.
  warnings.warn(

In [18]:
# Get the flux of ammonia uptake
sol_mbm_glucose.fluxes['EX_cpd00013_e0']

-6.931166657065474

In [19]:
# Try growing on L1 glucose
l1_glucose = media_definitions['l1'].copy()
l1_glucose['EX_cpd00027_e0'] = 10

In [20]:
model.medium = clean_media(model, l1_glucose)
sol_l1_glucose = model.optimize()
sol_l1_glucose

/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00209_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd20826_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00240_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd03387_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd08438_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd11595_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00104_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd01826_e0, so it was not set in the media.
  warnings.warn(

In [21]:
# Add ammonia to the L1 glucose media
l1_glucose['EX_cpd00013_e0'] = 10
model.medium = clean_media(model, l1_glucose)
sol_l1_glucose_w_ammonia = model.optimize()
sol_l1_glucose_w_ammonia

/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00209_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd20826_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00240_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd03387_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd08438_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd11595_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd00104_e0, so it was not set in the media.
  warnings.warn(
/Users/helenscott/Documents/PhD/Segre-lab/GEM-utils/gem_utilities/media.py:31: UserWarning: Model does not have the exchange reaction EX_cpd01826_e0, so it was not set in the media.
  warnings.warn(